# ----- COOKIE -----
[cookie]
name = "wamsession"
key = "9767462fde7e41fca8f3bb1ed9f6000d7849e99b1d97a88c756f66364137c7a1"
expiry_days = 30

# ----- ROLES (group -> users) -----
[roles]
admin = ["admin", "suvo", "shivangi"]
user  = ["client1", "client2"]

# ----- USERS (nested tables) -----
[users]

[users.admin]
name = "Main Admin"
username = "admin"
password = "$2b$12$qVN3TC8BwxRNFvW.CrceXu.SIxSnH5QuDQHMHHSu4wNpvHK7AghdS"

[users.suvo]
name = "Suvo Das"
username = "suvo"
password = "$2b$12$I.8/LIRORPdDiUZlVt8ZcOPZIsIgK7bulD6LbElgaknoOYc13P8oO"

[users.shivangi]
name = "Shivangi"
username = "shivangi"
password = "$2b$12$q0eN1wg5z8m2uVw2YJIUoOtMaWXLSD4fRlqo03cNgk5T3UTNtkd7m"

[users.client1]
name = "Client One"
username = "client1"
password = "$2b$12$omDazl/CQaZXnFCzcyS.Tu3yCpNColONjts.CCwOrZr493AU7Ia2."

[users.client2]
name = "Client Two"
username = "client2"
password = "$2b$12$LQZawpOt8XW7PA3Qpf6i3enAG/1I8p5iHPJVSY3tpsxMMhqBHgS3q"
